### ISSUE TITLE
Training script error

### ISSUE THREAD

**Issue by diossynvax** [aryopg/vaxformer#3]
Hello

I'm trying to implement the Vaxformer program and I'm currently having difficulty with the train.py script. I suspect the problem may be that I'm preparing the .npy files incorrectly but I'm wondering if you could offer some guidance with where I'm going wrong.

When running the train.py script, the command:

immunogenicity_scores = np.load(immunogenicity_scores_filepath)

Creates the following error:

    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

If I set 'allow_pickle=True' then I get:

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

I assume the issue is with the format of the file but any advise you could give would be appreciated.

Many thanks

**Comment by aryopg** [comment]
Hi @diossynvax , thanks for your interest in using our code! It seems to be a shared issue across some people. We indeed suspect that it's because of the formatting.
Could you drop me a message at my university email (aryo.gema@ed.ac.uk) so that I can share with you our `*_score.npy` files? I think this would be the fastest way of remedying this problem for the moment.
